sealed-secrets:
  namespace: sealed-secrets
  ingress:
    enabled: true
    tls: true
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/issue-temporary-certificate: "false"
      cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    hostname: sealed-secrets.carstens.tech
